### ISSUE TITLE
Add SameSiteStatus.Unspecified

### ISSUE THREAD

**Issue by truemogician** [mingyaulee/WebExtensions.Net#4]
The SameSiteStatus enum has no member indicating value "unspecified", resulting in JsonException when the SameSite field of some cookies retrieved are unspecified.

**Comment by mingyaulee** [comment]
Hi, thanks for your contribution!

Two comments on this PR:
1. The JavaScript files shouldn't be changed and shouldn't produce any error since optional chaining is supported by all the JS runtime.
2. The enum file is generated dynamically so any change here will be overwritten the next time the generator runs.

I am not going to merge this but I will look into a way of adding this enum when it gets generated.

**Comment by mingyaulee** [comment]
Fixed in v0.7.3
