### ISSUE TITLE
Is there any way post message to ContentScript.razor  from Popup.razor?

### ISSUE THREAD

**Issue by hanxiao123** [mingyaulee/WebExtensions.Net#68]
in v1.3,Is there any simple way to post message to ContentScript.razor  from Popup.razor?
My ideal way is below,but it's not work.
in Popup.razor
WebExtensions.Runtime.SendMessage("",obj,null)

in ContentScript.razor：

   protected override async Task OnInitializedAsync()
   {
       await WebExtensions.Runtime.OnMessage.AddListener(HandMsg);
   }

**Comment by mingyaulee** [comment]
Another method overload for sendMessage has been added in v2.1.0

**Comment by hanxiao123** [comment]
Is there any Test project or example about new way to sendMessage?

**Comment by mingyaulee** [comment]
There is no sample showing it unfortunately. I am thinking of creating a sample project for messaging or maybe even implementing a simpler messaging broker so that it can be more intuitive. I will look more into it when I get some free time.

You can try out the approach suggested in the stack overflow answer by using `Tabs.SendMessage` API from the popup to send a message to the content script.

**Comment by mingyaulee** [comment]
[Messaging samples project](https://github.com/mingyaulee/Blazor.BrowserExtension.Samples/tree/main/Messaging) has been added!
