### ISSUE TITLE
brower.menus bind error in chrome

### ISSUE THREAD

**Issue by yuzd** [mingyaulee/WebExtensions.Net#8]
![image](https://user-images.githubusercontent.com/16083659/132117977-64dbbd61-202f-4d34-bc5e-55092b28bd27.png)

![image](https://dimg04.c-ctrip.com/images/0v56k120008y1wlfl476D.png)

![image](https://dimg04.c-ctrip.com/images/0v56r120008y1x4143819.png)

**Comment by mingyaulee** [comment]
An API for `contextMenus` need to be added separately for Chrome. The `menus` API is only supported by Firefox.

**Comment by mingyaulee** [comment]
A proxy API for `contextMenus` has been added in v0.9.2.

You can use it from the new property `webExtensionsApi.ContextMenus`, but be aware that this will not work in Firefox because Firefox only has `browser.menus`.

**Additional note:**
This was raised as an issue in [Mozilla browser polyfill](https://github.com/mozilla/webextension-polyfill/issues/242) and it has been decided that the polyfill will not to support this. A workaround as mentioned in the issue is to do something like `if (!browser.menus) browser.menus = browser.contextMenus;` before you start using the API.

**Comment by yuzd** [comment]
nice job
